### ISSUE TITLE
base.tplとdb.pyをgitの管理対象に含める

### ISSUE THREAD

**Issue by c-bata** [akaikumako/System-Englishwords#1]
## 概要

いくつかのファイルがgitの管理対象に含まれてないみたいです
パッと見た感じ下の2つのファイルですね

* `db.py`
* `views/base.tpl`

後は `.gitignore` 追加しとくといいかと思います。

## github issueについて

ご存知かもだけど、githubのissueはgitのコミットメッセージから閉じる事ができます。

参考: http://tipshare.info/view/4eb4f72f4b2122e92a000000

```
$ git add db.py views/base.tpl
$ git commit -m "close #1 コミットメッセージ"
```

**Comment by akaikumako** [comment]
ご指摘ありがとうございます(_ _)
管理対象に追加完了しました！

**Comment by c-bata** [comment]
:+1:
